language: objective-c
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - gem update cocoapods
xcode_workspace: FBKVOController.xcworkspace
xcode_scheme: FBKVOController
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
