language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
  - gem install slather
xcode_workspace: FBKVOController.xcworkspace
xcode_scheme: FBKVOController
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
after_success:
  - slather
